# fly.toml app configuration file generated for guidely-api on 2025-07-21T00:36:36+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'guidely-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false        # App will NOT suspend
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'

[processes]
  app = "uvicorn api.main:app --host 0.0.0.0 --port 8080"