apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  # This is the name of your Cloud Run service.
  name: guidely-service
  annotations:
    # Allows for deployment via the 'gcloud run deploy' command.
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # This annotation helps define container startup order if you had multiple containers (e.g., a sidecar).
        run.googleapis.com/container-dependencies: "{}"
    spec:
      containerConcurrency: 80 # Max concurrent requests per container instance.
      timeoutSeconds: 300      # Max request processing time.
      containers:
        # IMPORTANT: This image path is a placeholder. 
        # Our CI/CD pipeline will replace this with the actual image path after a successful build.
        - image: gcr.io/region-ai/guidely:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            # --- Runtime Environment Variables ---
            # These values are injected securely from Google Secret Manager at startup.
            - name: NODE_ENV # Set to production for deployed environments.
              value: "production"
            - name: GOOGLE_CLOUD_PROJECT_ID
              valueFrom: { secretKeyRef: { name: google-cloud-project-id, key: "latest" } }
            - name: GEMINI_API_KEY
              valueFrom: { secretKeyRef: { name: gemini-api-key, key: "latest" } }
            - name: MONGODB_URI
              valueFrom: { secretKeyRef: { name: mongodb-uri, key: "latest" } }
            - name: SERPAPI_KEY
              valueFrom: { secretKeyRef: { name: serpapi-key, key: "latest" } }
          resources:
            limits:
              cpu: "1000m"    # 1 vCPU
              memory: "512Mi" # 512 Megabytes