name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # This checks out your code

      - name: Show repo root contents
        run: ls -la ${{ github.workspace }}
        # Debug: See what’s at repo root

      - name: Show backend directory contents
        run: |
          if [ -d "${{ github.workspace }}/backend" ]; then
            echo "Found backend directory:"
            ls -la "${{ github.workspace }}/backend"
          else
            echo "ERROR: backend directory not found!"
            exit 1
          fi
        # Debug: Fail early if backend folder is missing

      - name: Install backend dependencies
        working-directory: backend
        run: |
          if [ -f package.json ]; then
            npm ci
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No recognized dependency file found in backend."
          fi
        # Installs dependencies for Node or Python backend

      - name: Run backend tests
        working-directory: backend
        run: |
          if [ -f package.json ]; then
            npm test
          elif [ -f pytest.ini ] || [ -f requirements.txt ]; then
            pytest || python -m unittest discover
          else
            echo "No test runner configured."
          fi
        # Runs backend tests for Node or Python

      # Add more steps below as needed (build, deploy, etc.)
