name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug: show repo root contents
        run: ls -la

      - name: Debug: show api folder contents
        run: |
          if [ -d "api" ]; then
            ls -la "api"
          else
            echo "ERROR: api directory not found!"
            exit 1
          fi

      - name: Install Python dependencies
        working-directory: api
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "ERROR: requirements.txt not found in api/"
            exit 1
          fi

      - name: Run backend tests
        working-directory: api
        run: |
          pytest
