name: Deploy to Google Cloud Run

on:
  # This workflow is triggered on the successful completion of the "Build and Push Docker Image" workflow.
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    # Only run this job if the triggering workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Deploy to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'regional-ai-backend' # <-- CHANGE THIS to your desired Cloud Run service name
          region: 'us-central1' # <-- CHANGE THIS to your preferred GCP region
          # Use the image that was just built and pushed by the previous workflow.
          image: 'ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_sha }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Output service URL'
        run: echo "Service deployed to ${{ steps.deploy.outputs.url }}"